_BATCH_ACCOUNT_NAME = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Your batch account name
_BATCH_ACCOUNT_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Your batch account key
_BATCH_ACCOUNT_URL = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Your batch account URL
_STORAGE_ACCOUNT_NAME = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Your storage account name
_STORAGE_ACCOUNT_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Your storage account key
_POOL_ID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Your Pool ID
_POOL_NODE_COUNT = 2  # Pool node count
_POOL_VM_SIZE = 'STANDARD_D16_v3'  # VM Type/Size
_JOB_ID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'  # Job ID
_STANDARD_OUT_FILE_NAME = 'stdout.txt'  # Standard Output file
_STANDARD_ERR_FILE_NAME = 'stderr.txt'  # Standard Error file

_TASK_FILE = "task.py"
_OUTBUCKET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

_TIMEOUT = 480
